// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	models "pois/models"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// CreateAlias provides a mock function with given fields: _a0
func (_m *Store) CreateAlias(_a0 models.Alias) (models.Alias, error) {
	ret := _m.Called(_a0)

	var r0 models.Alias
	if rf, ok := ret.Get(0).(func(models.Alias) models.Alias); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Alias)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Alias) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSchedule provides a mock function with given fields: _a0
func (_m *Store) CreateSchedule(_a0 models.Schedule) (models.Schedule, error) {
	ret := _m.Called(_a0)

	var r0 models.Schedule
	if rf, ok := ret.Get(0).(func(models.Schedule) models.Schedule); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Schedule)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.Schedule) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAlias provides a mock function with given fields: _a0, _a1
func (_m *Store) DeleteAlias(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSchedule provides a mock function with given fields: _a0, _a1
func (_m *Store) DeleteSchedule(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAlias provides a mock function with given fields: _a0
func (_m *Store) FindAlias(_a0 string) ([]models.Alias, error) {
	ret := _m.Called(_a0)

	var r0 []models.Alias
	if rf, ok := ret.Get(0).(func(string) []models.Alias); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Alias)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSchedule provides a mock function with given fields: _a0, _a1
func (_m *Store) FindSchedule(_a0 string, _a1 string) ([]models.Schedule, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []models.Schedule
	if rf, ok := ret.Get(0).(func(string, string) []models.Schedule); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Schedule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStore(t mockConstructorTestingTNewStore) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
